# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: action.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'action.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import enums_pb2 as enums__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x61\x63tion.proto\x1a\x0b\x65nums.proto\"K\n\x12SwitchActiveAction\x12\x14\n\x0c\x63haracter_id\x18\x02 \x01(\x11\x12\x1f\n\x17\x63haracter_definition_id\x18\x03 \x01(\r\"m\n\x0ePlayCardAction\x12\x0f\n\x07\x63\x61rd_id\x18\x02 \x01(\x11\x12\x1a\n\x12\x63\x61rd_definition_id\x18\x05 \x01(\r\x12\x12\n\ntarget_ids\x18\x03 \x03(\x11\x12\x1a\n\x12will_be_effectless\x18\x04 \x01(\x08\"\x7f\n\x0eUseSkillAction\x12\x1b\n\x13skill_definition_id\x18\x02 \x01(\x05\x12\x12\n\ntarget_ids\x18\x03 \x03(\x11\x12\"\n\x15main_damage_target_id\x18\x04 \x01(\x11H\x00\x88\x01\x01\x42\x18\n\x16_main_damage_target_id\"P\n\x15\x45lementalTuningAction\x12\x17\n\x0fremoved_card_id\x18\x02 \x01(\x11\x12\x1e\n\x0btarget_dice\x18\x03 \x01(\x0e\x32\t.DiceType\"\x12\n\x10\x44\x65\x63lareEndActionB\x0e\xaa\x02\x0bGiTcg.Protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'action_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\013GiTcg.Proto'
  _globals['_SWITCHACTIVEACTION']._serialized_start=29
  _globals['_SWITCHACTIVEACTION']._serialized_end=104
  _globals['_PLAYCARDACTION']._serialized_start=106
  _globals['_PLAYCARDACTION']._serialized_end=215
  _globals['_USESKILLACTION']._serialized_start=217
  _globals['_USESKILLACTION']._serialized_end=344
  _globals['_ELEMENTALTUNINGACTION']._serialized_start=346
  _globals['_ELEMENTALTUNINGACTION']._serialized_end=426
  _globals['_DECLAREENDACTION']._serialized_start=428
  _globals['_DECLAREENDACTION']._serialized_end=446
# @@protoc_insertion_point(module_scope)
