# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: preview.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'preview.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import mutation_pb2 as mutation__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rpreview.proto\x1a\x0emutation.proto\"\xe7\x02\n\x0bPreviewData\x12(\n\rswitch_active\x18\x06 \x01(\x0b\x32\x0f.SwitchActiveEMH\x00\x12(\n\rcreate_entity\x18\n \x01(\x0b\x32\x0f.CreateEntityEMH\x00\x12(\n\rremove_entity\x18\x0b \x01(\x0b\x32\x0f.RemoveEntityEMH\x00\x12/\n\x11modify_entity_var\x18\x0c \x01(\x0b\x32\x12.ModifyEntityVarEMH\x00\x12\x36\n\x14transform_definition\x18\r \x01(\x0b\x32\x16.TransformDefinitionEMH\x00\x12\x1b\n\x06\x64\x61mage\x18\x0f \x01(\x0b\x32\t.DamageEMH\x00\x12\"\n\napply_aura\x18\x10 \x01(\x0b\x32\x0c.ApplyAuraEMH\x00\x12$\n\x0bmove_entity\x18\x1c \x01(\x0b\x32\r.MoveEntityEMH\x00\x42\n\n\x08mutationB\x0e\xaa\x02\x0bGiTcg.Protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'preview_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\013GiTcg.Proto'
  _globals['_PREVIEWDATA']._serialized_start=34
  _globals['_PREVIEWDATA']._serialized_end=393
# @@protoc_insertion_point(module_scope)
